### ISSUE TITLE
how to use this?

### ISSUE THREAD

**Issue by bluetulip89** [ankur-tiwari/basic-gps-lisnener#1]
I found your code in GitHub search and its great. May I know how to integrate/use your code for AIS140 standard tracking? Can you help me out. I need your support in configuring the transmitter / sender GPS module. thanks in advance

**Comment by ankur-tiwari** [comment]
You can setup node environment on your server. Open the required port for me I'm using `port 5008` you can choose any port and change it inside the script. Just run the script `node app.js` or `node yourfile.js`. To run the script forever you can use `pm2` on your server. When ever you change anything inside your script just 'pm2 restart yourfile.js'

**Comment by bluetulip89** [comment]
Thank you for your immediate reply. I have done this in my server. How to configure the AIS140 GPS Device to send data to this server?

With Regards,

Mr. Rajarajan.E, 
Bluetronics. 

    On Thursday, November 5, 2020, 07:42:11 AM GMT+5:30, Ankur Tiwari <notifications@github.com> wrote:  
 
 


You can setup node environment on your server. Open the required port for me I'm using port 5008 you can choose any port and change it inside the script. Just run the script node app.js or node yourfile.js. To run the script forever you can use pm2 on your server. When ever you change anything inside your script just 'pm2 restart yourfile.js'

**Comment by bluetulip89** [comment]
And if you are not bothered, Can I ask you a thing? I saw your status in GitHub as a guy looking for a new role. Are you still looking at or got one already? 
If you are still looking for a new role, Can you send the following details:1. Work Experience / Hands-on experience with programming languages. 2. resume.3.Contact details. 
Thanks in advance. 
With Regards,

Mr. Rajarajan.E, 


    On Thursday, November 5, 2020, 07:46:03 AM GMT+5:30, raja rajan <rajarajanelango@ymail.com> wrote:  
 
 Thank you for your immediate reply. I have done this in my server. How to configure the AIS140 GPS Device to send data to this server?

With Regards,

Mr. Rajarajan.E, 
Bluetronics. 

    On Thursday, November 5, 2020, 07:42:11 AM GMT+5:30, Ankur Tiwari <notifications@github.com> wrote:  
 
 


You can setup node environment on your server. Open the required port for me I'm using port 5008 you can choose any port and change it inside the script. Just run the script node app.js or node yourfile.js. To run the script forever you can use pm2 on your server. When ever you change anything inside your script just 'pm2 restart yourfile.js'

**Comment by ankur-tiwari** [comment]
@bluetulip89 Thanks for the asking, Right now I'm working in a startup [Gyrix Technolabs](https://gyrix.co/). And holding a stack in it and we are open to take any kind of work related to our field. Let me know if you need more details on this. Thanks have a good day.

**Comment by ankur-tiwari** [comment]
Added README.md file in the project, Closing this issues
